import { StyleSheet, Platform, Dimensions } from "react-native";
import { COLORS, SHADOWS } from "../../constants/theme";

const { width, height } = Dimensions.get("window");

export const VIBE = {
  primary: "#6366F1",
  secondary: "#F59E0B",
  success: "#10B981",
  danger: "#EF4444",
  info: "#3B82F6",
  purple: "#8B5CF6",
  bg: "#F8FAFC",
  surface: "#FFFFFF",
  text: "#1E293B",
  muted: "#64748B",
  border: "#E2E8F0",
};

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: VIBE.bg },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  header: {
    backgroundColor: "transparent",
    zIndex: 1000,
  },
  headerTop: {
    paddingHorizontal: 15,
    paddingTop: Platform.OS === "ios" ? 40 : 20,
    paddingBottom: 20,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    zIndex: 1,
    ...SHADOWS.medium,
    elevation: 10,
  },
  navBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 5,
  },
  headerIconBtn: {
    width: 38,
    height: 38,
    borderRadius: 10,
    backgroundColor: "rgba(255,255,255,0.15)",
    justifyContent: "center",
    alignItems: "center",
    ...Platform.select({
      web: { cursor: 'pointer' } as any,
      default: {}
    }),
  },
  titleCenter: { alignItems: "center" },
  headerTitle: { fontSize: 18, fontWeight: "900", color: "#fff" },
  headerSub: {
    fontSize: 9,
    fontWeight: "800",
    color: "rgba(255,255,255,0.65)",
    letterSpacing: 1.5,
  },
  selectorGrid: { flexDirection: "row", gap: 6 },
  glassPill: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 10,
    padding: 6,
    ...Platform.select({
      web: { cursor: 'pointer' } as any,
      default: {}
    }),
  },
  glassLabel: {
    fontSize: 7,
    fontWeight: "900",
    color: "rgba(255,255,255,0.5)",
    marginBottom: 0,
  },
  glassValue: { fontSize: 11, fontWeight: "800", color: "#fff" },
  searchStrip: {
    flexDirection: "row",
    paddingHorizontal: 15,
    marginTop: -20,
    alignItems: "center",
    gap: 8,
    marginBottom: 12,
    zIndex: 1001,
    elevation: 21,
  },
  archiveToggle: {
    paddingHorizontal: 12,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#fff",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    ...SHADOWS.small,
    ...Platform.select({
      web: { cursor: 'pointer' } as any,
      default: {}
    }),
  },
  archiveToggleText: {
    fontSize: 10,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  searchBar: {
    flex: 1,
    minWidth: 140,
    height: 48,
    backgroundColor: "#fff",
    borderRadius: 24,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 15,
    ...SHADOWS.medium,
  },
  searchInput: {
    flex: 1,
    marginLeft: 8,
    fontSize: 13,
    fontWeight: "600",
    color: VIBE.text,
    paddingVertical: 10,
  },
  refreshRound: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",
    ...SHADOWS.small,
    ...Platform.select({
      web: { cursor: 'pointer' } as any,
      default: {}
    }),
  },
  modeToggleArea: { paddingHorizontal: 20, marginBottom: 20 },
  modeTabs: {
    flexDirection: "row",
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 5,
    ...SHADOWS.small,
  },
  modeTab: {
    flex: 1,
    height: 45,
    borderRadius: 12,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    ...Platform.select({
      web: { cursor: 'pointer' } as any,
      default: {}
    }),
  },
  activeModeTab: { backgroundColor: VIBE.primary, ...SHADOWS.medium },
  modeTabText: { fontSize: 12, fontWeight: "800", color: VIBE.muted },
  searchActionsScroll: {
    flex: 1,
  },
  searchActionsContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingRight: 4,
    paddingVertical: 5,
  },
  statsDashboard: { paddingHorizontal: 20, paddingBottom: 30, gap: 15 },
  statBox: {
    width: 180,
    height: 110,
    borderRadius: 30,
    padding: 20,
    justifyContent: "center",
    zIndex: 2,
    elevation: 3,
  },
  statLabel: {
    fontSize: 9,
    fontWeight: "900",
    color: "rgba(255,255,255,0.7)",
    letterSpacing: 1,
  },
  statValue: { fontSize: 20, fontWeight: "900", color: "#fff", marginTop: 5 },
  statIcon: { position: "absolute", bottom: 15, right: 15 },
  mainBody: { flex: 1 },
  listContainer: { flex: 1 },
  bulkActionStrip: {
    flexDirection: "row",
    paddingHorizontal: 20,
    paddingBottom: 20,
    alignItems: "center",
    gap: 15,
  },
  bulkInputContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    height: 56,
    borderRadius: 20,
    paddingHorizontal: 20,
    ...SHADOWS.small,
  },
  bulkSym: {
    fontSize: 18,
    fontWeight: "900",
    color: VIBE.primary,
    marginRight: 10,
  },
  bulkInput: { flex: 1, fontSize: 16, fontWeight: "700", color: VIBE.text },
  checkAllBtn: {
    alignItems: "center",
    gap: 4,
    ...Platform.select({
      web: { cursor: 'pointer' } as any,
      default: {}
    }),
  },
  checkAllText: { fontSize: 9, fontWeight: "900" },
  listHeaderRow: {
    flexDirection: "row",
    paddingHorizontal: 20,
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  listTitle: {
    fontSize: 12,
    fontWeight: "900",
    color: VIBE.muted,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  filterChips: { flexDirection: "row", gap: 8 },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 15,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: VIBE.border,
    ...Platform.select({
      web: { cursor: 'pointer' } as any,
      default: {}
    }),
  },
  filterChipText: { fontSize: 10, fontWeight: "900", color: VIBE.muted },
  flatListContent: { paddingBottom: 120 },
  cardWrapper: { marginBottom: 15, paddingHorizontal: 20 },
  financeCard: {
    backgroundColor: "#fff",
    borderRadius: 20,
    padding: 14,
    ...SHADOWS.small,
    borderWidth: 1,
    borderColor: VIBE.border,
    ...Platform.select({
      web: { cursor: 'pointer' } as any,
      default: {}
    }),
  },
  selectedCard: {
    borderColor: VIBE.primary,
    backgroundColor: VIBE.primary + "05",
  },
  statusIndicator: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 6,
    borderTopLeftRadius: 25,
    borderBottomLeftRadius: 25,
  },
  cardContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  leftSection: {
    flex: 1,
    flexDirection: "row",
    alignItems: "flex-start",
    minWidth: 0,
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 15,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 2,
  },
  avatarText: { fontSize: 20, fontWeight: "900" },
  mainInfo: { flex: 1, marginLeft: 15, minWidth: 0 },
  studentName: { fontSize: 15, fontWeight: "800", color: VIBE.text },
  tuitionBreakdown: {
    flexDirection: "row",
    gap: 12,
    marginTop: 6,
    marginBottom: 4,
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: "#F1F5F9",
  },
  breakdownItem: {
    flex: 1,
  },
  breakdownLabel: {
    fontSize: 7,
    fontWeight: "900",
    color: VIBE.muted,
    marginBottom: 1,
  },
  breakdownValue: {
    fontSize: 10,
    fontWeight: "800",
    color: VIBE.text,
  },
  debtBox: { flexDirection: "row", alignItems: "center", marginTop: 2 },
  debtLabel: { fontSize: 11, fontWeight: "600" },
  debtValue: { fontSize: 11, fontWeight: "800" },
  rightSection: {
    marginLeft: 10,
    alignItems: "flex-end",
    justifyContent: "center",
    minWidth: 80,
    flexShrink: 0,
  },
  billingBubble: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 15,
    backgroundColor: "#F1F5F9",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    width: 80,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    ...SHADOWS.small,
  },
  billingBubbleActive: {
    backgroundColor: VIBE.primary,
    borderColor: VIBE.primary,
  },
  billingBubbleOverride: {
    backgroundColor: VIBE.purple,
    borderColor: VIBE.purple,
  },
  bubbleSym: {
    fontSize: 14,
    fontWeight: "900",
    color: VIBE.muted,
    marginRight: 4,
  },
  bubbleInput: {
    fontSize: 14,
    fontWeight: "bold",
    color: VIBE.text,
    textAlign: "center",
    minWidth: 40,
    flexShrink: 1,
    padding: 0,
    ...(Platform.OS === "android" ? {} : { letterSpacing: 0.5 }),
  },
  actionIcons: { flexDirection: "row", alignItems: "center", gap: 12 },
  historyCircle: {
    width: 38,
    height: 38,
    borderRadius: 19,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: VIBE.bg,
  },
  ledgerButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: VIBE.primary,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    gap: 4,
    ...SHADOWS.small,
    ...Platform.select({
      web: { cursor: 'pointer' } as any,
      default: {}
    }),
  },
  ledgerButtonText: {
    fontSize: 10,
    fontWeight: "900",
    color: "#fff",
    letterSpacing: 0.5,
  },
  fabWrap: { position: "absolute", bottom: 30, left: 20, right: 20 },
  mainFab: {
    height: 64,
    borderRadius: 24,
    overflow: "hidden",
    ...SHADOWS.large,
    ...Platform.select({
      web: { cursor: 'pointer' } as any,
      default: {}
    }),
  },
  fabGrad: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
  },
  fabText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: 0.5,
  },
  overlay: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.6)",
    justifyContent: "flex-end",
    alignItems: "center",
    width: "100%",
  },
  overlayCenter: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.8)",
    justifyContent: "center",
    padding: 25,
    width: "100%",
  },
  sheetBody: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    padding: 25,
    maxHeight: height * 0.85,
    minHeight: height * 0.45,
    width: "100%",
    alignItems: "stretch",
    flexShrink: 1,
    elevation: 24,
    ...Platform.select({
      web: { boxShadow: "0 -10px 20px rgba(0,0,0,0.15)" },
      default: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -10 },
        shadowOpacity: 0.15,
        shadowRadius: 20,
      }
    })
  },
  sheetHandle: {
    width: 40,
    height: 5,
    backgroundColor: VIBE.border,
    borderRadius: 3,
    alignSelf: "center",
    marginBottom: 20,
  },
  sheetHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingBottom: 20,
    borderBottomWidth: 1,
    borderBottomColor: VIBE.border,
    marginBottom: 15,
    width: "100%",
  },
  sheetTitle: {
    flex: 1,
    fontSize: 18,
    fontWeight: "900",
    color: VIBE.text,
    textAlign: "left",
  },
  sheetList: {
    paddingVertical: 10,
    width: "100%",
    flexGrow: 1,
    paddingBottom: Platform.OS === "android" ? 80 : 40,
  },
  sheetItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 18,
    borderRadius: 15,
    marginBottom: 10,
    backgroundColor: "#F8FAFC",
    width: "100%",
    minHeight: 56,
    ...Platform.select({
      web: { cursor: 'pointer' } as any,
      default: {}
    }),
  },
  activeSheetItem: { backgroundColor: VIBE.primary + "10" },
  sheetItemText: {
    flex: 1,
    fontSize: 15,
    fontWeight: "700",
    color: VIBE.text,
    marginRight: 12,
  },
  activeSheetItemText: { color: VIBE.primary, fontWeight: "800" },
  paymentModal: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 45,
    borderTopRightRadius: 45,
    padding: 30,
    maxHeight: height * 0.9,
    width: "100%",
    alignItems: "stretch",
    flexShrink: 1,
  },
  modalTopRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 35,
  },
  modalStudentName: { fontSize: 20, fontWeight: "900", color: VIBE.text },
  closeRound: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: VIBE.bg,
    justifyContent: "center",
    alignItems: "center",
  },
  modalInputs: { gap: 15, marginBottom: 30 },
  pillInput: {
    backgroundColor: VIBE.bg,
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: VIBE.border,
    fontSize: 20,
    fontWeight: "900",
    color: VIBE.text,
  },
  methodGrid: { flexDirection: "row", gap: 10, marginBottom: 30 },
  methodBtn: {
    flex: 1,
    height: 48,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: VIBE.border,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: VIBE.bg,
  },
  methodText: { fontSize: 12, fontWeight: "800", color: VIBE.muted },
  saveBtn: {
    height: 64,
    borderRadius: 24,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
    ...SHADOWS.medium,
  },
  saveBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "900",
    letterSpacing: 1,
  },
  historyBlock: {
    marginTop: 40,
    borderTopWidth: 1,
    borderTopColor: VIBE.border,
    paddingTop: 35,
  },
  historyHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 25,
  },
  blockTitle: {
    fontSize: 15,
    fontWeight: "900",
    color: VIBE.text,
    letterSpacing: 0.5,
  },
  viewFullText: { fontSize: 13, fontWeight: "800" },
  transactionTile: {
    backgroundColor: VIBE.bg,
    padding: 20,
    borderRadius: 24,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: VIBE.border,
  },
  tileHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  tileAmt: { fontSize: 18, fontWeight: "900", color: VIBE.primary },
  tileDetail: { fontSize: 13, color: VIBE.text, fontWeight: "700" },
  tileDate: {
    fontSize: 11,
    color: VIBE.muted,
    fontWeight: "800",
    marginTop: 8,
  },
  noHistory: {
    textAlign: "center",
    color: VIBE.muted,
    marginTop: 20,
    fontStyle: "italic",
  },
  alertCard: {
    backgroundColor: "#fff",
    width: "100%",
    borderRadius: 35,
    padding: 30,
    alignItems: "center",
  },
  alertTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: VIBE.text,
    marginBottom: 12,
  },
  alertText: {
    fontSize: 14,
    color: VIBE.muted,
    textAlign: "center",
    lineHeight: 22,
    marginBottom: 35,
  },
  alertBtnRow: { flexDirection: "row", gap: 15 },
  alertBtnPri: {
    flex: 1.5,
    height: 60,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    ...SHADOWS.medium,
  },
  alertBtnSec: {
    flex: 1,
    height: 60,
    backgroundColor: VIBE.bg,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
  },
  alertBtnTextPri: { color: "#fff", fontWeight: "900", fontSize: 16 },
  alertBtnTextSec: { color: VIBE.text, fontWeight: "800", fontSize: 16 },
  emptyWrap: { alignItems: "center", marginTop: 100, opacity: 0.5 },
  emptyText: {
    fontSize: 18,
    fontWeight: "900",
    color: "#94A3B8",
    marginTop: 20,
  },
  emptyContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 40,
    marginTop: 60,
  },
  emptyTitle: {
    fontSize: 20,
    fontWeight: "900",
    color: "#1E293B",
    marginTop: 20,
    marginBottom: 10,
  },
  linkBtn: {
    paddingHorizontal: 30,
    paddingVertical: 15,
    borderRadius: 20,
    marginTop: 20,
    ...SHADOWS.medium,
  },
  linkBtnText: { color: "#fff", fontWeight: "800", fontSize: 16 },
  textWhite: { color: "#fff" },
  dateSelector: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: VIBE.bg,
    borderRadius: 15,
    padding: 15,
    marginBottom: 20,
    gap: 12,
  },
  dateText: {
    flex: 1,
    fontSize: 16,
    fontWeight: "700",
    color: VIBE.text,
  },
  dailyTotalCard: {
    backgroundColor: VIBE.primary + "10",
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
    marginBottom: 20,
  },
  dailyTotalLabel: {
    fontSize: 10,
    fontWeight: "900",
    color: VIBE.primary,
    ...(Platform.OS !== "android" && { letterSpacing: 1 }),
  },
  dailyTotalValue: {
    fontSize: 24,
    fontWeight: "900",
    color: VIBE.primary,
    marginTop: 5,
  },
  dailyPaymentItem: {
    flexDirection: "row",
    alignItems: "center",
    padding: 15,
    backgroundColor: "#fff",
    borderRadius: 15,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: VIBE.border,
  },
  dailyStudentName: {
    fontSize: 14,
    fontWeight: "800",
    color: VIBE.text,
  },
  dailyStudentClass: {
    fontSize: 11,
    color: VIBE.muted,
    fontWeight: "700",
    marginTop: 2,
  },
  dailyReceipt: {
    fontSize: 10,
    color: VIBE.muted,
    marginTop: 4,
  },
  dailyAmount: {
    fontSize: 16,
    fontWeight: "900",
    color: VIBE.success,
  },
  warningStrip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FEF3C7",
    padding: 12,
    marginHorizontal: 20,
    marginTop: 10,
    marginBottom: 20,
    borderRadius: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: "#F59E0B",
  },
  warningText: {
    flex: 1,
    fontSize: 11,
    color: "#92400E",
    fontWeight: "700",
  },
  warningLink: {
    fontSize: 11,
    color: VIBE.primary,
    fontWeight: "900",
    textDecorationLine: "underline",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 30,
  },
  errorTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#1E293B",
    marginTop: 20,
  },
  errorSub: {
    fontSize: 16,
    color: "#64748B",
    textAlign: "center",
    marginTop: 10,
    marginBottom: 30,
  },
  errorButton: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 25,
    paddingVertical: 15,
    borderRadius: 15,
    ...SHADOWS.medium,
  },
  errorButtonText: {
    fontSize: 16,
    fontWeight: "700",
    color: "#fff",
  },
  discountCard: {
    paddingVertical: 10,
    padding: 10,
  },
  discountCardContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  discountRightSection: {
    alignItems: "flex-end",
    justifyContent: "center",
    minWidth: 70,
    flexShrink: 0,
  },
  discountBubble: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 12,
    backgroundColor: "#F1F5F9",
    borderWidth: 1,
    borderColor: "#E2E8F0",
    width: 70,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    ...SHADOWS.small,
  },
  discountBubbleOverride: {
    backgroundColor: VIBE.success,
    borderColor: VIBE.success,
  },
  discountBubbleSym: {
    fontSize: 12,
    fontWeight: "900",
    color: VIBE.success,
    marginRight: 3,
  },
  discountBubbleInput: {
    fontSize: 13,
    fontWeight: "bold",
    color: VIBE.text,
    textAlign: "center",
    minWidth: 35,
    flexShrink: 1,
    padding: 0,
  },
  sectionLabel: {
    fontSize: 10,
    fontWeight: "900",
    color: VIBE.muted,
    marginLeft: 20,
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  breakdownContainer: { marginTop: 15 },
  breakdownScroll: { paddingHorizontal: 20, gap: 10, paddingBottom: 5 },
  breakdownCard: {
    backgroundColor: "#fff",
    padding: 12,
    borderRadius: 15,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
    borderColor: VIBE.border,
    minWidth: 120,
    ...SHADOWS.small,
  },
  typeIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
  },
  activeBreakdownCard: {
    backgroundColor: VIBE.primary,
    borderColor: VIBE.primary,
  },
  activeBreakdownLabel: { color: "rgba(255,255,255,0.8)" },
  activeBreakdownValue: { color: "#fff" },
  summaryBreakdownLabel: {
    fontSize: 9,
    fontWeight: "800",
    color: VIBE.muted,
    textTransform: "uppercase",
  },
  summaryBreakdownValue: {
    fontSize: 14,
    fontWeight: "900",
    color: VIBE.text,
    marginTop: 1,
  },
  filterInfoBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginHorizontal: 20,
    marginTop: 15,
    padding: 10,
    backgroundColor: VIBE.bg,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: VIBE.border,
  },
  filterInfoText: { fontSize: 12, fontWeight: "700", color: VIBE.muted },
});
