require("dotenv").config();

module.exports = ({ config }) => {
  // We prioritize eagles (Adehyeemba) as the default.
  // Normalize to lowercase to prevent case-sensitivity issues during lookup.
  const rawId = process.env.SCHOOL_ID || "eagles";
  // Maintain casing for school object keys (IBS is uppercase in the dictionary)
  const schoolId = rawId.toLowerCase() === "ibs" ? "IBS" : rawId; 

  const schools = {
    afahjoy: {
      name: "Gilead App",
      slug: "afahjoy",
      package: "com.eduease.afahjoy",
      scheme: "afahjoy",
      logo: "./assets/icon-gilead.png",
      hotline: "0249675302",
      fullName: "Gilead Educational Centre",
      motto: "Jehovah Our Refuge",
      address: "Papase No.2",
      email: "gileadeducatioalcentre703@gmail.com",
      primaryColor: "#F07F13",
      secondaryColor: "#000000",
      surfaceColor: "#FFF9F0",
      brandPrimary: "#F07F13",
      brandSecondary: "#000000",
      easProjectId: "52c5863c-ed22-412e-bdbd-59586c08a746",
      firebase: {
        apiKey: "AIzaSyCbCqe8YnkeIdpAXBG2v37k6lC8E9AuHPQ",
        authDomain: "afahjoy-7cc03.firebaseapp.com",
        projectId: "afahjoy-7cc03",
        storageBucket: "afahjoy-7cc03.firebasestorage.app",
        messagingSenderId: "605469464068",
        appId: "1:605469464068:web:83eaade7a07b3e07948751",
      },
    },
    beano: {
      name: "Beano App",
      slug: "beano",
      package: "com.saysmanage.beanoapp",
      scheme: "beano",
      logo: "./assets/icon-beano.png",
      hotline: "0243271572",
      fullName: "Beano Educational Institute",
      motto: "Knowledge is the key to Success",
      address: "Royal City, Papase No 2 - Kasoa",
      email: "",
      primaryColor: "#6A1B9A",
      secondaryColor: "#F57C00",
      surfaceColor: "#f3e7c1ff",
      brandPrimary: "#F57C00",
      brandSecondary: "#6A1B9A",
      easProjectId: null,
      firebase: {
        apiKey: "AIzaSyD5a6vaZoU3W2B99AJetvqXTNjcbCk4dAM",
        authDomain: "beano-app-a9c38.firebaseapp.com",
        projectId: "beano-app-a9c38",
        storageBucket: "beano-app-a9c38.firebasestorage.app",
        messagingSenderId: "505764175188",
        appId: "1:505764175188:web:2f14074c16b73073d87cc1",
      },
    },
    morgis: {
      name: "Great Legacy",
      slug: "morgis",
      package: "com.saysmanage.morgisapp",
      scheme: "morgis",
      logo: "./assets/icon-legacy.png",
      hotline: "0543646005",
      fullName: "Great Legacy Commission Academy",
      motto: "For A Better Future",
      address: "Praso Kumah-Abirem",
      email: "great.edu@gmail.com",
      primaryColor: "#FBC02D",
      secondaryColor: "#000000",
      surfaceColor: "#FDF7FF",
      brandPrimary: "#FFD700",
      brandSecondary: "#000000",
      easProjectId: "0489c74b-5405-4834-a802-5238ebb25e21",
      firebase: {
        apiKey: "AIzaSyBcwe68xp1qgBmzb3bGb41q6y5ZPR-TVrc",
        authDomain: "morgis-app.firebaseapp.com",
        projectId: "morgis-app",
        storageBucket: "morgis-app.firebasestorage.app",
        messagingSenderId: "629555287836",
        appId: "1:629555287836:web:f3cb9c20a8588454d8ccd9",
      },
    },
    IBS: {
      name: "IBS App",
      slug: "IBS",
      package: "com.saysmanage.jeiriver",
      scheme: "IBS",
      logo: "./assets/icon-ibs.png",
      hotline: "0279434358",
      fullName: "IBS Educational Complex",
      motto: "Christ is the Key",
      address: "Asankrangwa, Newtown",
      email: "bethesdamethodistschool@gmail.com",
      primaryColor: "#1C6E3C",
      secondaryColor: "#FFD700",
      surfaceColor: "#ecfcb1ff",
      brandPrimary: "#DAA520",
      brandSecondary: "#006400",
      easProjectId: null,
      firebase: {
        apiKey: "AIzaSyBcc6WCDNaUoRloASa2aZt4hPAvFZorK98",
        authDomain: "jei-river.firebaseapp.com",
        projectId: "jei-river",
        storageBucket: "jei-river.firebasestorage.app",
        messagingSenderId: "925332921968",
        appId: "1:925332921968:web:f84f98cb9d9d017cc6deb5",
      },
    },
    eagles: {
      name: "Adehyeemba",
      slug: "eagles",
      package: "com.saysmanage.eagleapp",
      scheme: "eagle",
      logo: "./assets/icon-aps.png",
      hotline: "+233545404397",
      fullName: "Adehyeemba Preparatory School",
      motto: "Edwumaden Ho Wo Mfaso",
      address: "Awutu Bawjiase",
      email: "",
      primaryColor: "#2c0964ff",
      secondaryColor: "#dd4364ff",
      surfaceColor: "#dcabf3ff",
      brandPrimary: "#cc315fff",
      brandSecondary: "#140e53ff",
      easProjectId: null,
      firebase: {
        apiKey: "AIzaSyBl_YXsJMsWHVDZkMKHk7HGxghp_XAM4L4",
        authDomain: "royal-lisben.firebaseapp.com",
        projectId: "royal-lisben",
        storageBucket: "royal-lisben.firebasestorage.app",
        messagingSenderId: "449092727389",
        appId: "1:449092727389:web:b5c7f563fadede614053b4",
      },
    },
    perfect: {
      name: "PEI End",
      slug: "perfect",
      package: "com.saysmanage.peiapp",
      scheme: "perfect",
      logo: "./assets/icon-perfect.png",
      hotline: "0536725643",
      fullName: "Perfect End International School",
      motto: "Don't Stop Until You're Proud",
      address: "Oklu Nkwanta, Off Bawjiase Rd, Kasoa",
      email: "info@perfectendintersch.com",
      primaryColor: "#C1272D",
      secondaryColor: "#1F4E79",
      surfaceColor: "#d3e6a1ff",
      brandPrimary: "#C1272D",
      brandSecondary: "#313030ff",
      easProjectId: null,
      firebase: {
        apiKey: "AIzaSyAEXlKLEDedM1jHnngwRQ2FG7wYy8libzg",
        authDomain: "clis-app-f89b8.firebaseapp.com",
        projectId: "clis-app-f89b8",
        storageBucket: "clis-app-f89b8.firebasestorage.app",
        messagingSenderId: "717015071628",
        appId: "1:717015071628:web:ec812e39dafbd8cfde74a9",
      },
    },
    creation: {
      name: "Creation Star",
      slug: "creation",
      package: "com.saysmanage.creation",
      scheme: "creation",
      logo: "./assets/icon-creation.png",
      hotline: "0279434358",
      fullName: "Creation Star Academy",
      motto: "God Our Hope",
      address: "Latebiokoshie, near Radio Gold",
      email: "",
      primaryColor: "#7A7D82",
      secondaryColor: "#f3c976ff",
      surfaceColor: "#FDF7FF",
      brandPrimary: "#686764ff",
      brandSecondary: "#f5cb78ff",
      easProjectId: null,
      firebase: {
        apiKey: "AIzaSyCj2_msgZVcreaNUkM8q2M8VkOWRd1Rgww",
        authDomain: "vince-app-c49a2.firebaseapp.com",
        projectId: "vince-app-c49a2",
        storageBucket: "vince-app-c49a2.firebasestorage.app",
        messagingSenderId: "232909106721",
        appId: "1:232909106721:web:ac2f17b4c888ff7561fd60",
      },
    },

    jewel: {
      name: "Jewel App",
      slug: "jewel",
      package: "com.saysmanage.jewel",
      scheme: "jewels",
      logo: "./assets/icon-jewel.png",
      hotline: "+233247725831",
      fullName: "Jewel Star Academy",
      motto: "The Fear Of The Lord",
      address: "Kasoa New Market Rd, Kasoa, Ghana",
      email: "",
      primaryColor: "#f0bf5eff",
      secondaryColor: "#6b4c2a",
      surfaceColor: "#d671b8ff",
      brandPrimary: "#5e67eeff",
      brandSecondary: "#f5c35eff",
      easProjectId: null,
      firebase: {
        apiKey: "AIzaSyBWAaIywN-rJyDUipU89yutw8bnIN5pr6I",
        authDomain: "jewels-app-17a30.firebaseapp.com",
        projectId: "jewels-app-17a30",
        storageBucket: "jewels-app-17a30.firebasestorage.app",
        messagingSenderId: "173597685845",
        appId: "1:173597685845:web:6adc074b3e6727a9d97cdc",
      },
    },

    clis: {
      name: "CLIS App",
      slug: "clis",
      package: "com.saysmanage.clis",
      scheme: "clis",
      logo: "./assets/icon-clis.png",
      hotline: "023 375 7458",
      fullName: "Christ Legacy International School",
      motto: "As Precious As Diamond",
      address: "Off Bawjiase Road, 100 meters from the New Market, Kasoa",
      email: "",
      primaryColor: "#3cca48ff",
      secondaryColor: "#2a552dff",
      surfaceColor: "#96d494ff",
      brandPrimary: "#3cca48ff",
      brandSecondary: "#2a552dff",
      easProjectId: null,
      firebase: {
        apiKey: "AIzaSyD8R5rncXH135QyTdoyuxHCLUvqf2O0_d0",
        authDomain: "clis-app-e39e8.firebaseapp.com",
        projectId: "clis-app-e39e8",
        storageBucket: "clis-app-e39e8.firebasestorage.app",
        messagingSenderId: "605761169592",
        appId: "1:605761169592:web:667ca88d55dff6f16aec4d",
      },
    },
    model: {
      name: "Model Power",
      slug: "modelpower",
      package: "com.saysmanage.modelpower",
      scheme: "modelpower",
      logo: "./assets/icon-modelpower.png",
      hotline: "0548950370",
      fullName: "Model Power Academy",
      motto: "Your Excellence is Assured",
      address: "Greater Accra Region, GA West Municipal",
      email: "",
      primaryColor: "#D4AF37",
      secondaryColor: "#228B22",
      surfaceColor: "#FDF7FF",
      brandPrimary: "#D4AF37",
      brandSecondary: "#000000",
      easProjectId: null,
      firebase: {
        apiKey: "AIzaSyBlWYOx1I_u8VwJf7puo8I0uFvktAo3yl8",
        authDomain: "model-power-430de.firebaseapp.com",
        projectId: "model-power-430de",
        storageBucket: "model-power-430de.firebasestorage.app",
        messagingSenderId: "735827883706",
        appId: "1:735827883706:web:2149b0cbce03eaa7f13483",
      },
    },

    stone: {
      name: "Stepping Stone",
      slug: "stone",
      package: "com.saysmanage.stone",
      scheme: "stone",
      logo: "./assets/icon-stone.png",
      hotline: "0548950370",
      fullName: "Stepping Stone Educational Centre",
      motto: "Sowing seeds of Knowlede",
      address: "Tamale, Northern Ghana",
      email: "Steppingstoneeducentres@gmail.com",
      primaryColor: "#7a0b1aff",
      secondaryColor: "#228B22",
      surfaceColor: "#f7f6d1ff",
      brandPrimary: "#2c5af1ff",
      brandSecondary: "#7a0b1aff",
      easProjectId: null,
      firebase: {
        apiKey: "AIzaSyAfaTh7LCjUnO50-8XrRpuzj4_GzMJiSzc",
        authDomain: "stepping-stone-90720.firebaseapp.com",
        projectId: "stepping-stone-90720",
        storageBucket: "stepping-stone-90720.firebasestorage.app",
        messagingSenderId: "42632915971",
        appId: "1:42632915971:web:9c08287a875c5987297236",
      },
    },
    brain: {
      name: "Bright Brain",
      slug: "brain",
      package: "com.saysmanage.brain",
      scheme: "brain",
      logo: "./assets/icon-brain.png",
      hotline: "0552530930",
      fullName: "Bright Brains Montessori School",
      motto: "God Our Hope",
      address: "Otukunor Street, Accra, Ghana",
      email: "brightbrains2018@gmail.com",
      primaryColor: "#7B2CBF",
      secondaryColor: "#FF4FA3",
      surfaceColor: "#FDF7FF",
      brandPrimary: "#7B2CBF",
      brandSecondary: "#3333d8ff",
      easProjectId: null,
      firebase: {
        apiKey: "AIzaSyBrRD_azmsbS1cbsmMA9YCI2QZFVHmkvlE",
        authDomain: "bright-brain-99daa.firebaseapp.com",
        projectId: "bright-brain-99daa",
        storageBucket: "bright-brain-99daa.firebasestorage.app",
        messagingSenderId: "592128740440",
        appId: "1:592128740440:web:5a2d6f6c3f26fd0b248e2d",
      },
    },
    cascom: {
      name: "CASCOM App",
      slug: "cascon",
      package: "com.saysmanage.cascom",
      scheme: "cascom",
      logo: "./assets/icon-cascom.png",
      hotline: "0279434358",
      fullName: "Christ Apostolic School Complex",
      motto: "Christ our Solid Foundation",
      address: "Tanoso, Techiman",
      email: "",
      primaryColor: "#0D47A1",
      secondaryColor: "#D32F2F",
      surfaceColor: "#8aa3f5ff",
      brandPrimary: "#D32F2F",
      brandSecondary: "#0D47A1",
      easProjectId: null,
      firebase: {
        apiKey: "AIzaSyDlWpkZokwVwr_drW1Q1y4t529cnpre9lM",
        authDomain: "cascom-59b61.firebaseapp.com",
        projectId: "cascom-59b61",
        storageBucket: "cascom-59b61.firebasestorage.app",
        messagingSenderId: "121225001260",
        appId: "1:121225001260:web:fd141544f12ae285389489",
      },
    },
    bms: {
      name: "BMS App",
      slug: "bms",
      package: "com.saysmanage.bms",
      scheme: "bms",
      logo: "./assets/icon-bms.png",
      hotline: "0248292545 / 0599548606",
      fullName: "Bethesda Methodist School",
      motto: "Aim High",
      address: "Abgogba",
      email: "",
      primaryColor: "#FEDD00",
      secondaryColor: "#1A237E",
      surfaceColor: "#dce099ff",
      brandPrimary: "#1A237E",
      brandSecondary: "#FEDD00",
      easProjectId: null,
      firebase: {
        apiKey: "AIzaSyCy1yDrktbt2eeiV5Qvvm1sXNwHcZtvY78",
        authDomain: "bms-app-f4572.firebaseapp.com",
        projectId: "bms-app-f4572",
        storageBucket: "bms-app-f4572.firebasestorage.app",
        messagingSenderId: "705991105475",
        appId: "1:705991105475:web:d103e15b1399f38e003b76",
      },
    },
    kent: {
      name: "KIS App",
      slug: "kent",
      package: "com.saysmanage.martbeck",
      scheme: "kent",
      logo: "./assets/icon-kent.png",
      hotline: "0540126050",
      fullName: "Kent International School",
      motto: "God Our Hope",
      address: "New Aplaku, Kent City Street 139st",
      email: "",
      primaryColor: "#006B3F",
      secondaryColor: "#F9A825",
      surfaceColor: "#edeeb0ff",
      brandPrimary: "#C62828",
      brandSecondary: "#006B3F",
      easProjectId: null,
      firebase: {
        apiKey: "AIzaSyAahcHdPoNvPEsfKfiSGcmu7_D6OQnE-Zs",
        authDomain: "golden-rock-16bf8.firebaseapp.com",
        projectId: "golden-rock-16bf8",
        storageBucket: "golden-rock-16bf8.firebasestorage.app",
        messagingSenderId: "623470853110",
        appId: "1:623470853110:web:3f6545a1cd7ace1a2525d7",
      },
    },
    bishops: {
      name: "Bishop App",
      slug: "bishops",
      package: "com.saysmanage.firstapp",
      scheme: "bishops",
      logo: "./assets/icon-bishop.png",
      hotline: "0273122929",
      fullName: "Bishop's Gate Educational School Complex",
      motto: "Integrity, Excellence and Wholeness",
      address: "Off Jei River Rd, Kasoa, Ghana",
      email: "bishop@gmail.com",
      primaryColor: "#1E4D8C",
      secondaryColor: "#D4AF37",
      surfaceColor: "#FAFAFA",
      brandPrimary: "#D4AF37",
      brandSecondary: "#1E4D8C",
      easProjectId: null,
      firebase: {
        apiKey: "AIzaSyBiFvOQZ0Rvao6NnhH42CtRqtfGpVAuvzE",
        authDomain: "thess-app.firebaseapp.com",
        projectId: "thess-app",
        storageBucket: "thess-app.firebasestorage.app",
        messagingSenderId: "151847614946",
        appId: "1:151847614946:web:123b3e2a2202a0098f9c22",
      },
    },
  };

  const selected = schools[schoolId] || schools["eagles"];
  const googleFile = `./services/${schoolId}/google-services.json`;

  return {
    ...config,
    name: selected.name,
    slug: selected.slug,
    scheme: selected.scheme,
    version: "1.0.0",
    orientation: "portrait",
    icon: selected.logo,
    userInterfaceStyle: "automatic",
    newArchEnabled: true,
    ios: {
      supportsTablet: true,
      bundleIdentifier: selected.package,
    },
    android: {
      package: selected.package,
      googleServicesFile: googleFile,
      adaptiveIcon: {
        foregroundImage: selected.logo,
        backgroundColor: "#ffffff",
      },
      edgeToEdgeEnabled: true,
    },
    web: {
      bundler: "metro",
      output: "static",
      baseUrl: "./",
    },
    plugins: [
      "expo-router",
      "expo-asset",
      "expo-video",
      [
        "expo-build-properties",
        {
          android: {
            // Deprecated field removed as per Expo guidance
          },
          ios: {
            // Deprecated field removed as per Expo guidance
          },
        },
      ],
    ],
    extra: {
      schoolId: selected.slug,
      schoolData: process.env.NODE_ENV === "production" ? null : schools,
      schoolFullName: selected.fullName,
      schoolHotline: selected.hotline,
      schoolAddress: selected.address,
      schoolEmail: selected.email,
      motto: selected.motto,
      primaryColor: selected.primaryColor,
      secondaryColor: selected.secondaryColor,
      surfaceColor: selected.surfaceColor,
      brandPrimary: selected.brandPrimary || selected.primaryColor,
      brandSecondary: selected.brandSecondary || selected.secondaryColor,
      firebase: selected.firebase,
      ...(selected.easProjectId
        ? { eas: { projectId: selected.easProjectId } }
        : {}),
    },
  };
};
