import { StyleSheet, Dimensions } from "react-native";
import { COLORS, SHADOWS } from "../../constants/theme";

const { width } = Dimensions.get("window");

export const VIBE = {
  primary: "#4F46E5", // Indigo
  secondary: "#F59E0B", // Amber
  success: "#10B981", // Emerald
  info: "#0EA5E9", // Sky
  purple: "#8B5CF6", // Violet
  danger: "#EF4444", // Rose
  bg: "#F8FAFC", // Lighter Slate
  surface: "#FFFFFF",
  text: "#0F172A",
  muted: "#64748B",
  border: "#E2E8F0",
  card: "#FFFFFF",
  chart1: "#6366F1",
  chart2: "#A855F7",
  chart3: "#EC4899",
};

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: VIBE.bg },
  centerContent: { flex: 1, justifyContent: "center", alignItems: "center" },
  centerText: { marginTop: 16, color: VIBE.muted, fontSize: 16 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: VIBE.surface,
    borderBottomWidth: 1,
    borderBottomColor: VIBE.border,
  },
  backButton: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: VIBE.bg,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 10,
  },
  headerTitle: { flex: 1, marginRight: 8 },
  headerTitleText: { fontSize: 18, fontWeight: "800", color: VIBE.text },
  headerSubtitle: { fontSize: 11, color: VIBE.muted, marginTop: 0 },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  actionIconButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: VIBE.bg,
    justifyContent: "center",
    alignItems: "center",
  },
  adminBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: VIBE.primary,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
    gap: 4,
  },
  adminBadgeText: { fontSize: 10, fontWeight: "900", color: "#fff" },
  dateRangeText: {
    fontSize: 12,
    color: VIBE.muted,
    fontWeight: "600",
    marginTop: -2,
  },
  overviewSection: { padding: 20 },
  sectionHeaderRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  periodIndicator: {
    backgroundColor: VIBE.bg,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: VIBE.border,
  },
  periodIndicatorText: {
    fontSize: 11,
    fontWeight: "700",
    color: VIBE.muted,
  },
  mainBalanceCard: {
    width: "100%",
    padding: 24,
    borderRadius: 28,
    ...SHADOWS.medium,
    marginBottom: 12,
    minHeight: 140,
    justifyContent: "center",
    elevation: 8,
  },
  mainBalanceHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  mainBalanceLabel: {
    color: "#ffffffCC",
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  mainBalanceValue: {
    color: "#fff",
    fontSize: 32,
    fontWeight: "900",
  },
  mainBalanceFooter: {
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#ffffff20",
  },
  mainBalanceSubtext: {
    color: "#ffffffB3",
    fontSize: 12,
    fontWeight: "600",
  },
  secondaryOverviewRow: {
    flexDirection: "row",
    width: "100%",
    gap: 12,
    marginTop: 8,
  },
  secondaryCard: {
    flex: 1,
    backgroundColor: VIBE.surface,
    padding: 16,
    borderRadius: 24,
    borderLeftWidth: 6,
    justifyContent: "center",
    minHeight: 100,
    elevation: 4,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
  },
  secondaryLabel: {
    fontSize: 11,
    fontWeight: "800",
    color: VIBE.muted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  secondaryValue: {
    fontSize: 22,
    fontWeight: "900",
    includeFontPadding: false,
  },
  section: { paddingHorizontal: 20, paddingBottom: 20 },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: VIBE.text,
    marginBottom: 4,
  },
  sectionSubtitle: {
    fontSize: 14,
    color: VIBE.muted,
    marginBottom: 16,
  },
  overviewCards: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 12,
  },
  overviewCard: {
    flex: 1,
    minWidth: "45%",
    padding: 20,
    borderRadius: 24,
    justifyContent: "center",
  },
  overviewLabel: {
    fontSize: 11,
    fontWeight: "800",
    textTransform: "uppercase",
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  overviewValue: {
    fontSize: 22,
    fontWeight: "900",
  },
  categoryCard: {
    backgroundColor: VIBE.surface,
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    ...SHADOWS.medium,
  },
  categoryHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  categoryIconBox: {
    width: 50,
    height: 50,
    borderRadius: 16,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 14,
  },
  categoryTitleRow: {
    flex: 1,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  categoryName: {
    fontSize: 17,
    fontWeight: "800",
    color: VIBE.text,
  },
  categoryTermLabel: {
    fontSize: 11,
    color: VIBE.muted,
    fontWeight: "600",
    marginTop: 1,
  },
  categoryTotal: {
    fontSize: 20,
    fontWeight: "900",
  },
  periodsGrid: {
    flexDirection: "row",
    gap: 10,
  },
  periodItem: {
    flex: 1,
    backgroundColor: VIBE.bg,
    padding: 12,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  periodLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: VIBE.muted,
    textTransform: "uppercase",
    marginBottom: 6,
  },
  periodValue: {
    fontSize: 13,
    fontWeight: "800",
    color: VIBE.text,
    includeFontPadding: false,
  },
  periodBadge: {
    backgroundColor: VIBE.surface,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    marginTop: 4,
  },
  periodCount: {
    fontSize: 9,
    fontWeight: "700",
    color: VIBE.primary,
  },
  healthCard: {
    backgroundColor: VIBE.surface,
    padding: 20,
    borderRadius: 24,
    ...SHADOWS.medium,
  },
  healthRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  healthLabel: { fontSize: 15, fontWeight: "800", color: VIBE.text },
  healthValue: { fontSize: 16, fontWeight: "900" },
  healthBarContainer: {
    height: 10,
    backgroundColor: VIBE.bg,
    borderRadius: 5,
    overflow: "hidden",
    marginBottom: 14,
  },
  healthBar: {
    height: "100%",
    borderRadius: 5,
  },
  healthFooter: {
    fontSize: 12,
    color: VIBE.muted,
    fontWeight: "600",
    lineHeight: 18,
  },
  quickActionsRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 4,
  },
  quickActionBtn: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    backgroundColor: VIBE.surface,
    padding: 16,
    borderRadius: 18,
    ...SHADOWS.medium,
  },
  quickActionText: { fontSize: 14, fontWeight: "700" },
  toggleContainer: {
    flexDirection: "row",
    backgroundColor: VIBE.border,
    marginHorizontal: 20,
    marginBottom: 20,
    borderRadius: 16,
    padding: 4,
    height: 48,
  },
  toggleBtn: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
  },
  toggleBtnActive: {
    backgroundColor: VIBE.surface,
    ...SHADOWS.medium,
  },
  toggleText: {
    fontSize: 14,
    fontWeight: "700",
    color: VIBE.muted,
  },
  toggleTextActive: {
    color: VIBE.primary,
  },
  dailyTotalsContainer: {
    marginTop: 10,
  },
  dailyRow: {
    backgroundColor: VIBE.surface,
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    ...SHADOWS.medium,
    borderWidth: 1,
    borderColor: VIBE.bg,
  },
  dailyHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: VIBE.bg,
    marginBottom: 16,
  },
  dailyDate: {
    fontSize: 17,
    fontWeight: "800",
    color: VIBE.text,
  },
  dailyYear: {
    fontSize: 12,
    color: VIBE.muted,
    fontWeight: "600",
  },
  dailySummaryRight: {
    alignItems: "flex-end",
  },
  dailyRevenue: {
    fontSize: 16,
    fontWeight: "900",
  },
  dailyExpense: {
    fontSize: 13,
    fontWeight: "700",
    marginTop: 2,
  },
  dailyGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    rowGap: 16,
    columnGap: 8,
  },
  dailyStat: {
    width: "30%",
  },
  dailyStatLabel: {
    fontSize: 10,
    fontWeight: "800",
    color: VIBE.muted,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  dailyStatValue: {
    fontSize: 14,
    fontWeight: "700",
    color: VIBE.text,
    marginTop: 4,
    includeFontPadding: false,
  },
  dailyNetBadge: {
    width: "100%",
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 8,
  },
  dailyNetText: {
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.5,
    includeFontPadding: false,
  },
  ledgerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  ledgerItem: {
    flex: 1,
    alignItems: "center",
  },
  ledgerValue: {
    fontSize: 16,
    fontWeight: "900",
    color: VIBE.text,
  },
});
